import {
  normalizeFixedApplicationProfile,
  type ApplicationAward,
  type ApplicationPublication,
  type FixedApplicationProfile,
} from "./application-profile";

export const OWNER_PROFILE_DATA_REVISION = 2026082303;

const awards: ApplicationAward[] = [
  {
    name: "Vanderbilt University Provost's Pathbreaking Discovery Award",
    type: "individual",
    date: "2026",
    issuer: "Vanderbilt University",
    descriptionZh: "范德堡大学研究生院授予的个人学术荣誉，表彰在学术成就、研究影响力和原创发现方面表现突出的研究生。Xinyu Zhang 入选 2026 年获奖者名单。",
    descriptionEn: "An individual Vanderbilt Graduate School honor recognizing exceptional academic achievement, scholarly impact, and original discovery. Xinyu Zhang was named among the 2026 recipients.",
  },
  {
    name: "NIH Replication Prize",
    type: "team",
    date: "2026-04",
    issuer: "National Institutes of Health (NIH)",
    descriptionZh: "美国国立卫生研究院设立的团队奖项，表彰推动生物医学研究可重复性、严谨性与透明度的可实施策略。本人为四人获奖团队成员之一。",
    descriptionEn: "A team prize from the National Institutes of Health recognizing actionable strategies that advance rigor, transparency, and replication in biomedical research. Awarded as one member of a four-person team.",
  },
  {
    name: "NSF SMI 2026 Student Travel Award",
    type: "individual",
    date: "2026",
    issuer: "National Science Foundation (NSF)",
    descriptionZh: "由美国国家科学基金会支持的竞争性学生差旅奖，用于支持学生参加 2026 Statistics in Medical Imaging Conference 并开展统计成像领域的学术交流。该奖为会议差旅资助，不是科研项目经费。",
    descriptionEn: "A competitive NSF-supported student travel award for participation in the 2026 Statistics in Medical Imaging Conference and scholarly exchange in statistical imaging. This is conference travel support, not a research grant.",
  },
];

const publications: ApplicationPublication[] = [
  {
    title: "Semiparametric confidence sets for cross-sectional and longitudinal neuroimaging",
    authorOrderZh: "第一作者、通讯作者",
    authorOrderEn: "First Author and Corresponding Author",
    date: "2025-10-31",
    venue: "Imaging Neuroscience",
    bestVerifiedRank: "JCR Q2",
    jcrQuartile: "JCR Q2",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1162/IMAG.a.965",
    descriptionZh: "提出适用于横断面与纵向神经影像数据的半参数置信集方法，在控制多重比较错误的同时评估效应大小是否超过具有实际意义的阈值。",
    descriptionEn: "Develops semiparametric confidence sets for cross-sectional and longitudinal neuroimaging, controlling multiplicity while assessing whether effect sizes exceed practically meaningful thresholds.",
  },
  {
    title: "Statistical considerations for evaluating treatment effect under various non-proportional hazard scenarios",
    authorOrderZh: "第一作者",
    authorOrderEn: "First Author",
    date: "2025-02-11",
    venue: "Statistical Methods in Medical Research",
    bestVerifiedRank: "JCR Q1",
    jcrQuartile: "JCR Q1",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1177/09622802241313297",
    descriptionZh: "系统比较非比例风险情形下多种治疗效应估计与检验方法，为肿瘤临床试验中的终点分析和方法选择提供统计依据。",
    descriptionEn: "Systematically compares treatment-effect estimation and testing approaches under non-proportional hazards to inform endpoint analysis and method selection in oncology trials.",
  },
  {
    title: "Multi-shot diffusion tensor imaging in the lumbosacral spinal cord: characterizing heterogeneity in healthy tissue and differences in multiple sclerosis",
    authorOrderZh: "第二作者",
    authorOrderEn: "Second Author",
    date: "2026-07-08",
    venue: "Imaging Neuroscience",
    bestVerifiedRank: "JCR Q2",
    jcrQuartile: "JCR Q2",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1162/IMAG.a.1296",
    descriptionZh: "利用多次激发弥散张量成像刻画健康腰骶脊髓组织的空间异质性，并评估多发性硬化患者与健康对照之间的差异。",
    descriptionEn: "Uses multi-shot diffusion tensor imaging to characterize spatial heterogeneity in healthy lumbosacral spinal cord tissue and differences associated with multiple sclerosis.",
  },
  {
    title: "Exploring trajectories of anxiety symptoms in autistic and non-autistic youth over adolescence using parent- and self-report measures",
    authorOrderZh: "第三作者",
    authorOrderEn: "Third Author",
    date: "2026-01-23",
    venue: "Research in Autism Spectrum Disorders",
    bestVerifiedRank: "JCR Q1",
    jcrQuartile: "JCR Q1",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1016/j.reia.2026.202830",
    descriptionZh: "结合家长报告与青少年自评数据，研究自闭症与非自闭症青少年在青春期的焦虑症状发展轨迹及报告者差异。",
    descriptionEn: "Examines trajectories of anxiety symptoms across adolescence in autistic and non-autistic youth using complementary parent- and self-report measures.",
  },
  {
    title: "Changes in functional connectivity in relapsing-remitting multiple sclerosis spinal cord measured via region-based and data-driven analyses",
    authorOrderZh: "第四作者",
    authorOrderEn: "Fourth Author",
    date: "2025-06-20",
    venue: "Imaging Neuroscience",
    bestVerifiedRank: "JCR Q2",
    jcrQuartile: "JCR Q2",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1162/IMAG.a.51",
    descriptionZh: "通过基于脑区和数据驱动的分析方法，研究复发缓解型多发性硬化患者脊髓功能连接的变化。",
    descriptionEn: "Measures changes in spinal-cord functional connectivity in relapsing-remitting multiple sclerosis using both region-based and data-driven analyses.",
  },
  {
    title: "Long short-term memory on abstract syntax tree for SQL injection detection",
    authorOrderZh: "第三作者",
    authorOrderEn: "Third Author",
    date: "2021-03-12",
    venue: "IET Software",
    bestVerifiedRank: "JCR Q3",
    jcrQuartile: "JCR Q3",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1049/sfw2.12018",
    descriptionZh: "将 SQL 语句的抽象语法树表示与长短期记忆网络结合，用于识别 SQL 注入攻击并提升结构化代码特征的利用效率。",
    descriptionEn: "Combines abstract syntax tree representations of SQL statements with long short-term memory networks for SQL injection detection.",
  },
  {
    title: "Length of stay in the neonatal ICU is predictable using heart rate: an opportunity for optimizing managed care",
    authorOrderZh: "第一作者",
    authorOrderEn: "First Author",
    date: "2021-12-09",
    venue: "2021 43rd Annual International Conference of the IEEE Engineering in Medicine & Biology Society (EMBC)",
    bestVerifiedRank: "",
    jcrQuartile: "",
    casQuartile: "",
    ccfCategory: "",
    status: "Published",
    url: "https://doi.org/10.1109/EMBC46164.2021.9629847",
    descriptionZh: "基于新生儿心率信息预测新生儿重症监护病房住院时长，探索支持护理资源配置和管理优化的早期预测机会。",
    descriptionEn: "Uses neonatal heart-rate information to predict neonatal intensive-care length of stay and support earlier planning of managed-care resources.",
  },
  {
    title: "Multi-modal and multi-region distance model for neuroimaging: application to ABCD study",
    authorOrderZh: "第一作者",
    authorOrderEn: "First Author",
    date: "2026-01-22",
    venue: "Annals of Applied Statistics",
    bestVerifiedRank: "JCR Q2",
    jcrQuartile: "JCR Q2",
    casQuartile: "",
    ccfCategory: "",
    status: "Preprint; Major Revision",
    url: "",
    descriptionZh: "构建多模态、多脑区距离模型，用于整合神经影像信息并研究 ABCD 数据中的脑表型关联结构。",
    descriptionEn: "Develops a multimodal, multiregion distance model for integrating neuroimaging information and studying brain-phenotype association structure in the ABCD Study.",
  },
  {
    title: "Asymptotic distribution of the Robust Effect Size Index",
    authorOrderZh: "第一作者",
    authorOrderEn: "First Author",
    date: "2026-01-26",
    venue: "Psychometrika",
    bestVerifiedRank: "JCR Q1",
    jcrQuartile: "JCR Q1",
    casQuartile: "",
    ccfCategory: "",
    status: "Preprint; Under Review",
    url: "https://arxiv.org/abs/2601.19004",
    descriptionZh: "推导 Robust Effect Size Index 的渐近分布，为稳健效应量的统计推断、区间估计和大样本性质提供理论基础。",
    descriptionEn: "Derives the asymptotic distribution of the Robust Effect Size Index, providing a theoretical basis for inference and interval estimation of robust effect magnitude.",
  },
  {
    title: "Improved Estimation of Correlation Accuracy for Machine Learning Brain-Phenotype Associations",
    authorOrderZh: "第三作者",
    authorOrderEn: "Third Author",
    date: "2025-12-01",
    venue: "bioRxiv",
    bestVerifiedRank: "",
    jcrQuartile: "",
    casQuartile: "",
    ccfCategory: "",
    status: "Preprint; Journal Status Unknown",
    url: "",
    descriptionZh: "研究机器学习脑影像与表型关联中相关性准确度的估计问题，改进对预测关联强度和不确定性的评估。",
    descriptionEn: "Improves estimation of correlation accuracy for machine-learning brain-phenotype associations, with emphasis on evaluating predictive association strength and uncertainty.",
  },
  {
    title: "Optimized multi-echo gradient echo MRI of the lumbosacral spinal cord to investigate atrophy, lesion burden, and disability in relapsing-remitting multiple sclerosis",
    authorOrderZh: "第二作者",
    authorOrderEn: "Second Author",
    date: "",
    venue: "Imaging Neuroscience",
    bestVerifiedRank: "JCR Q2",
    jcrQuartile: "JCR Q2",
    casQuartile: "",
    ccfCategory: "",
    status: "First Revision",
    url: "",
    descriptionZh: "优化腰骶脊髓多回波梯度回波 MRI，用于评估复发缓解型多发性硬化中的萎缩、病灶负担与残障关联。",
    descriptionEn: "Optimizes multi-echo gradient-echo MRI of the lumbosacral spinal cord to investigate atrophy, lesion burden, and disability in relapsing-remitting multiple sclerosis.",
  },
];

export function applyOwnerApplicationProfileUpgrade(
  email: string,
  profile: FixedApplicationProfile,
) {
  if (email.trim().toLowerCase() !== "ivyzzzhang@gmail.com") {
    return { profile, changed: false };
  }
  if (profile.dataRevision >= OWNER_PROFILE_DATA_REVISION) {
    return { profile, changed: false };
  }
  const upgraded = normalizeFixedApplicationProfile({
    ...profile,
    dataRevision: OWNER_PROFILE_DATA_REVISION,
    identity: {
      ...profile.identity,
      firstName: "Xinyu",
      lastName: "Zhang",
      email: "xinyu.zhang@vanderbilt.edu",
      chineseFullName: "张馨予",
      chineseFirstName: "馨予",
      chineseLastName: "张",
      chineseEmail: "xinyu.zhang@vanderbilt.edu",
      usPhone: "+1 (475) 216-5398",
      chinaPhone: "+86 (158) 4047-0437",
      wechat: "ivyzzzhang",
      nativePlaceZh: "四川省成都市",
      nativePlaceEn: "Chengdu, Sichuan, China",
      birthPlaceZh: "辽宁省沈阳市",
      birthPlaceEn: "Shenyang, Liaoning, China",
      genderZh: "女",
      genderEn: "Female",
      ethnicityZh: profile.identity.ethnicityZh || "汉族",
      ethnicityEn: profile.identity.ethnicityEn || "Han Chinese",
      dateOfBirth: profile.identity.dateOfBirth || "1999-01-11",
    },
    links: {
      linkedin: "https://www.linkedin.com/in/xinyu-zhang-312249214/",
      github: "https://github.com/XinyuIvy",
      website: "https://xinyuivy.github.io/",
    },
    awards,
    publications,
  });
  return { profile: upgraded, changed: true };
}
