CREATE TABLE `applications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company` text NOT NULL,
	`title` text NOT NULL,
	`region` text DEFAULT '美国' NOT NULL,
	`location` text DEFAULT '' NOT NULL,
	`track` text DEFAULT '' NOT NULL,
	`job_url` text DEFAULT '' NOT NULL,
	`source` text DEFAULT '公司官网' NOT NULL,
	`fit` integer DEFAULT 3 NOT NULL,
	`interest` integer DEFAULT 3 NOT NULL,
	`priority` text DEFAULT 'P2' NOT NULL,
	`status` text DEFAULT '已收藏' NOT NULL,
	`discovered_date` text DEFAULT '' NOT NULL,
	`applied_date` text DEFAULT '' NOT NULL,
	`follow_up_date` text DEFAULT '' NOT NULL,
	`next_action` text DEFAULT '研究JD' NOT NULL,
	`resume_version` text DEFAULT '' NOT NULL,
	`work_authorization` text DEFAULT '' NOT NULL,
	`interview_notes` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
