import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

function cleanSlug(value: string) {
  return value.toLowerCase().trim().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80) || "job";
}

function encodeBase64(text: string) {
  const bytes = new TextEncoder().encode(text);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function escapeLatex(value: string) {
  return value
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([#$%&_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function markdownToLatex(markdown: string) {
  const lines = markdown.split(/\r?\n/);
  const output = [
    "\\documentclass[10pt]{article}",
    "\\usepackage[margin=0.62in]{geometry}",
    "\\usepackage[hidelinks]{hyperref}",
    "\\usepackage{enumitem}",
    "\\setlist[itemize]{leftmargin=1.25em,itemsep=1pt,topsep=2pt}",
    "\\pagestyle{empty}",
    "\\begin{document}",
  ];
  let inList = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith("- ")) {
      if (!inList) { output.push("\\begin{itemize}"); inList = true; }
      output.push(`\\item ${escapeLatex(line.slice(2)).replace(/\\\*\\\*(.*?)\\\*\\\*/g, "\\textbf{$1}")}`);
      continue;
    }
    if (inList) { output.push("\\end{itemize}"); inList = false; }
    if (!line) { output.push(""); continue; }
    if (line.startsWith("# ")) output.push(`\\begin{center}{\\LARGE\\bfseries ${escapeLatex(line.slice(2))}}\\end{center}`);
    else if (line.startsWith("## ")) output.push(`\\section*{${escapeLatex(line.slice(3))}}`);
    else output.push(escapeLatex(line).replace(/\\\*\\\*(.*?)\\\*\\\*/g, "\\textbf{$1}"));
  }
  if (inList) output.push("\\end{itemize}");
  output.push("\\end{document}");
  return output.join("\n");
}

async function putFile(token: string, path: string, content: string, message: string) {
  const api = `https://api.github.com/repos/XinyuIvy/CV/contents/${path}`;
  const existing = await fetch(`${api}?ref=main`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "User-Agent": "Ivy-Job-Radar" },
  });
  const current = existing.ok ? await existing.json() as { sha?: string } : null;
  const response = await fetch(api, {
    method: "PUT",
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "Content-Type": "application/json", "User-Agent": "Ivy-Job-Radar" },
    body: JSON.stringify({ message, content: encodeBase64(content), branch: "main", ...(current?.sha ? { sha: current.sha } : {}) }),
  });
  if (!response.ok) throw new Error(await response.text());
  return response.json();
}

export async function POST(request: NextRequest) {
  const body = await request.json() as { company?: string; title?: string; track?: string; markdown?: string };
  const company = String(body.company || "Unknown company").trim();
  const title = String(body.title || "Target role").trim();
  const track = cleanSlug(String(body.track || "general"));
  const markdown = String(body.markdown || "").trim();
  if (!markdown) return NextResponse.json({ error: "CV content is required." }, { status: 400 });

  const { env } = await import("cloudflare:workers");
  const token = String(env.CV_GITHUB_TOKEN || "").trim();
  const folder = `generated/${cleanSlug(company)}/${cleanSlug(title)}`;
  const tex = markdownToLatex(markdown);
  if (!token) {
    return NextResponse.json({ ok: true, published: false, folder, markdown, tex, message: "CV_GITHUB_TOKEN is not configured; files were generated but not written to GitHub." });
  }

  const commitMessage = `Generate tailored ${track} CV for ${company} ${title}`;
  await putFile(token, `${folder}/cv.md`, markdown + "\n", commitMessage);
  await putFile(token, `${folder}/main.tex`, tex + "\n", commitMessage);
  await putFile(token, `${folder}/README.md`, `# ${company} - ${title}\n\nTrack: ${track}\n\nGenerated by Ivy Job Radar CV Tailor. Review every claim against master/FACT_MASTER.md before submission.\n`, commitMessage);
  return NextResponse.json({ ok: true, published: true, folder, githubUrl: `https://github.com/XinyuIvy/CV/tree/main/${folder}`, tex });
}
